### ISSUE TITLE
Add versioned release tag(s)

### ISSUE THREAD

**Issue by jsejcksn** [denolib/ms#5]
I can import now using commit hash like https://deno.land/x/ms@368ad2fad4477b6ad19bff696a6eaf57a4f627a0/ms.ts, but semver tags are much nicer.

See:
- https://deno.land/manual/linking_to_external_code#how-do-i-import-a-specific-version-of-a-module
- https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository

**Comment by kt3k** [comment]
Thank you for the suggestion!

I tagged 0.1.0 https://github.com/denolib/ms/releases/tag/0.1.0 and the following should work now.

```ts
import { ms } from "https://deno.land/x/ms@0.1.0/ms.ts";
console.log(ms(1000));
```

**Comment by jsejcksn** [comment]
@kt3k. Thanks! The conventional format is `vSEMVER`, (beginning with a literal v). You are obviously free to use whatever format you prefer, but consider surveying other community modules.

**Comment by kt3k** [comment]
@jsejcksn Thanks for the suggestion. Popular modules like `oak`, `servest`, `abc`, `denon` etc all seem using vX.Y.Z type tags. So I pushed v0.1.0 as well and will switch using this convention in the future. (The only exception I could find was `deno_webview` which uses X.Y.Z type tag, but that didn't seem popular one).
